version: "3.0"
services:
  databus:
    image: "dbpedia/databus"
    ports:
      - 3000:3000 # HTTP: web ui
      - 3001:8080 # HTTP: exposes search api
      - 4000:4000 # HTTPS: web ui (when proxy server is enabled)
      - 4001:4001 # HTTPS: exposes search api (when proxy server is enabled)
    environment: 
      DATABUS_RESOURCE_BASE_URL: ${DATABUS_RESOURCE_BASE_URL}
      DATABUS_DATABASE_URL: http://172.17.0.01:3002
      DATABUS_OIDC_ISSUER_BASE_URL: ${DATABUS_OIDC_ISSUER_BASE_URL}
      DATABUS_OIDC_CLIENT_ID: ${DATABUS_OIDC_CLIENT_ID}
      DATABUS_OIDC_SECRET: ${DATABUS_OIDC_SECRET}
      DATABUS_DEFAULT_CONTEXT_URL: https://downloads.dbpedia.org/databus/context.jsonld
      DATABUS_PROXY_SERVER_ENABLE: ${DATABUS_PROXY_SERVER_ENABLE}
      DATABUS_PROXY_SERVER_USE_ACME: ${DATABUS_PROXY_SERVER_USE_ACME}
      DATABUS_PROXY_SERVER_OWN_CERT: ${DATABUS_PROXY_SERVER_OWN_CERT} # When not using ACME, what is the name of the own certificate file?
      DATABUS_PROXY_SERVER_OWN_CERT_KEY: ${DATABUS_PROXY_SERVER_OWN_CERT_KEY} # When not using ACME, what is the name of the own certificate's key file?
      DATABUS_PROXY_SERVER_HOSTNAME: ${DATABUS_PROXY_SERVER_HOSTNAME} # What is the hostname of this machine, when using the proxy server?
    volumes:
      - ./data/keypair/:/databus/server/keypair
      - ./data/users/:/databus/server/users
      - ./data/tls/:/tls:ro
  gstore:
    image: "dbpedia/gstore"
    environment: 
      VIRT_USER: ${VIRTUOSO_USER}
      VIRT_PASS: ${VIRTUOSO_PASSWORD}
      VIRT_URI: "http://172.17.0.01:3003"
      GIT_ROOT: "/root/git"
    ports:
      - "3002:80"
    volumes:
      - ./data/repo:/root/git
  virtuoso:
    image: "openlink/virtuoso-opensource-7"
    environment:
      DBA_PASSWORD: ${VIRTUOSO_PASSWORD}
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: ${DATABUS_RESOURCE_BASE_URL}
    ports:
      - "3003:8890"
    volumes:
      - ./data/virtuoso:/database
