version: "3.0"
services:
  lookup-servlet:
    #image: lookup-servlet
    build: .
    ports:
      - 8080:8080
    volumes: 
      - ./app-config-servlet.yml:/root/app-config.yml
      - ./index:/databus/search/index
