# Starts everything except the databus
version: "3.0"
services:
  lookup-servlet:
    image: lookup-servlet
    container_name: devenv_lookup
    ports:
      - 8080:8080
    volumes: 
      - ../search/app-config-servlet.yml:/root/app-config.yml
      - ../search/index:/databus/search/index
  gstore:
    image: dbpedia/gstore
    container_name: devenv_gstore
    environment: 
      VIRT_USER: "dba"
      VIRT_PASS: "everyoneknows"
      VIRT_URI: "http://172.17.0.01:3003"
      GIT_ROOT: "/root/git"
    ports:
      - "3002:80"
    volumes:
      - ./data/repo:/root/git
  virtuoso:
    logging:
      driver: none
    image: "openlink/virtuoso-opensource-7"
    container_name: devenv_virtuoso
    environment:
      DBA_PASSWORD: "everyoneknows"
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://localhost:3000"
    ports:
      - "3003:8890"
    volumes: 
      - ./data/virtuoso:/data
