# Starts everything except the databus
version: "3.0"
services:
  lookup-servlet:
    image: lookup-servlet
    container_name: devenv_lookup
    ports:
      - 8080:8080
    volumes: 
      - ../search/app-config-servlet.yml:/root/app-config.yml
      - ../search/index:/databus/search/index
  gstore:
    image: dbpedia/gstore:dev
    container_name: devenv_gstore
    environment: 
      STORAGE_USER: "dba"
      STORAGE_PASS: "everyoneknows"
      STORAGE_SPARQL_ENDPOINT_URI: http://virtuoso:8890/sparql
    ports:
      - "3002:8080"
    volumes:
      - ./data/gstore/git:/gstore/git
      - ./data/gstore/logs:/gstore/logs
  virtuoso:
    image: "pkleef/virtuoso-opensource-7:latest"
    container_name: devenv_virtuoso
    environment:
      DBA_PASSWORD: "everyoneknows"
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://localhost:3000"
    ports:
      - "3003:8890"
    volumes: 
      - ./data/virtuoso:/database
    entrypoint: /bin/bash -c "
        echo 'grant SPARQL_LOAD_SERVICE_DATA to \"SPARQL\";' > /opt/virtuoso-opensource/initdb.d/ini.sql &&
        echo 'grant SPARQL_SPONGE to \"SPARQL\";' >> /opt/virtuoso-opensource/initdb.d/ini.sql &&
        echo 'grant SPARQL_SELECT_FED to \"SPARQL\";' > /opt/virtuoso-opensource/initdb.d/ini.sql &&
        /virtuoso-entrypoint.sh
      "
      
  
